[libraries]
androidGradlePlugin = "com.android.tools.build:gradle:8.7.2"
maven-publish-gradlePlugin = "com.vanniktech:gradle-maven-publish-plugin:0.30.0"

androidx-annotations = "androidx.annotation:annotation:1.9.1"
androidx-appCompat = "androidx.appcompat:appcompat:1.6.1"
androidx-coordinatorLayout = "androidx.coordinatorlayout:coordinatorlayout:1.2.0"
androidx-multidex = "androidx.multidex:multidex:2.0.1"
androidx-viewPager = "androidx.viewpager:viewpager:1.0.0"

material = "com.google.android.material:material:1.11.0"
playServices-maps = "com.google.android.gms:play-services-maps:17.0.1"
